version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env.production
    ports:
      - 5432:5432

  pqadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 5050:80
    env_file:
      - .env.production
    depends_on:
      - db
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${SERVICE_PORT}
    restart: always
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    environment:
      SERVICE_PORT: ${SERVICE_PORT}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      NODE_ENV: production
    env_file:
      - .env.production
    depends_on:
      - db

volumes:
  db_data:
    driver: local
  pgadmin_data:
    driver: local
