version: '3.9'

services:
  db:
    container_name: postgres_dev
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pqadmin:
    container_name: pgadmin_dev
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data_dev:/var/lib/pgadmin
    ports:
      - 5050:80
    depends_on:
      - db
  app:
    container_name: app_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PORT: ${SERVICE_PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    environment:
      SERVICE_PORT: ${SERVICE_PORT}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      DEPLOY_TYPE: docker
    depends_on:
      - db

volumes:
  db_data_dev:
    driver: local
  pgadmin_data_dev:
    driver: local
